In [1]:
# Python 3.x Utility Functions
# From https://github.com/norvig/pytudes/blob/master/ipynb/Advent 2017.ipynb

import re
import numpy as np
import math
import random
import urllib.request

from collections import Counter, defaultdict, namedtuple, deque, abc, OrderedDict
from functools   import lru_cache, reduce
from itertools   import (permutations, combinations, chain, cycle, product, islice, 
                         takewhile, zip_longest, count as count_from)
from heapq       import heappop, heappush

identity = lambda x: x
letters  = 'abcdefghijklmnopqrstuvwxyz'

cat = ''.join

Ø   = frozenset() # Empty set
inf = float('inf')
BIG = 10 ** 999

In [2]:
#Part01

In [32]:
def insert_into(array, old_position, step, value):
    l = len(array)
    new_position = (old_position + step) % l
    tmp_array = np.insert(array, new_position + 1 , value)
   # np.copyto(array, tmp_array)
    return tmp_array, new_position + 1
    

In [27]:
part1 = np.array([0])
pos = 0
step = 3
val = 1

In [28]:
part1, pos = insert_into(part1, pos, step, val)

[0 1]
0


In [29]:
val += 1
part1, pos = insert_into(part1, pos, step, val)

[0 2 1]
0


In [30]:
val += 1
insert_into(part1, pos, step, val)

[0 2 3 1]
1


(array([0, 2, 3, 1]), 2)

In [49]:
part1 = np.array([0])
pos = 0
step = 312
val = 1
for i in range(2017):
    part1, pos = insert_into(part1, pos, step, val)
    val += 1

In [51]:
part1[(np.where(2017 == part1)[0]+1,)]

array([772])

In [55]:
part1 = np.array([0])
pos = 0
step = 312
val = 1
for i in range(1, 50000001):
    pos = (pos + step) % i + 1
    if pos == 1:
        print(i)

1
7
18
21
149
163
432
1690
2442
3574
3847
5315
439936
526278
3188902
9138330
42729050


In [38]:
part1[1525:1535]

array([ 478, 2016, 1512, 1134,  151, 2017,  638, 1513,  851, 1135])