In [1]:
# Python 3.x Utility Functions
# From https://github.com/norvig/pytudes/blob/master/ipynb/Advent 2017.ipynb

import re
import numpy as np
import math
import random
import urllib.request

from collections import Counter, defaultdict, namedtuple, deque, abc, OrderedDict
from functools   import lru_cache
from itertools   import (permutations, combinations, chain, cycle, product, islice, 
                         takewhile, zip_longest, count as count_from)
from heapq       import heappop, heappush

identity = lambda x: x
letters  = 'abcdefghijklmnopqrstuvwxyz'

cat = ''.join

Ø   = frozenset() # Empty set
inf = float('inf')
BIG = 10 ** 999

# Day06
# Part 1

Example
-------

In [59]:
ex = np.array([0, 2, 7, 0])

In [60]:
current = ex
l = len(current)
memory = np.empty((0,l), int)
cycle = 0
while True:
    cycle += 1
    max_ix = np.argmax(current)
    to_give = current[max_ix]
    memory = np.vstack((memory, current))
    current[max_ix] = 0
    for i in range(to_give):
        current[(max_ix + 1 + i ) % l] += 1
    print(current)
    if np.any((memory == current).all(axis = 1)):
        break
print(cycle)

[2 4 1 2]
[3 1 2 3]
[0 2 3 4]
[1 3 4 1]
[2 4 1 2]
5


### Read input file

In [68]:
input_f = np.fromfile('input.txt', sep = " ", dtype= 'i')

In [69]:
current = input_f
l = len(current)
memory = np.empty((0,l), int)
cycle = 0
while True:
    cycle += 1
    max_ix = np.argmax(current)
    to_give = current[max_ix]
    memory = np.vstack((memory, current))
    current[max_ix] = 0
    for i in range(to_give):
        current[(max_ix + 1 + i ) % l] += 1
    if np.any((memory == current).all(axis = 1)):
        break
print(cycle)

7864


## Part 2

In [80]:
ex = np.array([0, 2, 7, 0])
current = ex
l = len(current)
memory = np.empty((0,l), int)
cycle = 0
while True:
    cycle += 1
    max_ix = np.argmax(current)
    to_give = current[max_ix]
    memory = np.vstack((memory, current))
    current[max_ix] = 0
    for i in range(to_give):
        current[(max_ix + 1 + i ) % l] += 1
    print(current)
    comparison = (memory == current).all(axis = 1)
    print(comparison)
    if np.sum(comparison) > 1:
        break
print(cycle)
print(np.diff(np.where(comparison)))

[2 4 1 2]
[False]
[3 1 2 3]
[False False]
[0 2 3 4]
[False False False]
[1 3 4 1]
[False False False False]
[2 4 1 2]
[False  True False False False]
[3 1 2 3]
[False False  True False False False]
[0 2 3 4]
[False False False  True False False False]
[1 3 4 1]
[False False False False  True False False False]
[2 4 1 2]
[False  True False False False  True False False False]
9
[[4]]


In [81]:
input_f = np.fromfile('input.txt', sep = " ", dtype= 'i')
current = input_f
l = len(current)
memory = np.empty((0,l), int)
cycle = 0
while True:
    cycle += 1
    max_ix = np.argmax(current)
    to_give = current[max_ix]
    memory = np.vstack((memory, current))
    current[max_ix] = 0
    for i in range(to_give):
        current[(max_ix + 1 + i ) % l] += 1
    comparison = (memory == current).all(axis = 1)
    if np.sum(comparison) > 1:
        break
print(cycle)
print(np.diff(np.where(comparison)))

9559
[[1695]]
