In [1]:
# Python 3.x Utility Functions
# From https://github.com/norvig/pytudes/blob/master/ipynb/Advent 2017.ipynb

import re
import numpy as np
import math
import random
import urllib.request

from collections import Counter, defaultdict, namedtuple, deque, abc, OrderedDict
from functools   import lru_cache
from itertools   import (permutations, combinations, chain, cycle, product, islice, 
                         takewhile, zip_longest, count as count_from)
from heapq       import heappop, heappush

identity = lambda x: x
letters  = 'abcdefghijklmnopqrstuvwxyz'

cat = ''.join

Ø   = frozenset() # Empty set
inf = float('inf')
BIG = 10 ** 999

In [2]:
# Read file
input_a = np.fromfile(file = 'input.txt', sep = "\t")

In [3]:
input_array = np.reshape(input_a, (16,16))

In [4]:
input_array


array([[ 3751.,  3769.,  2769.,  2039.,  2794.,   240.,  3579.,  1228.,
         4291.,   220.,   324.,  3960.,   211.,  1346.,   237.,  1586.],
       [  550.,   589.,   538.,   110.,   167.,   567.,    99.,   203.,
          524.,   288.,   500.,   111.,   118.,   185.,   505.,    74.],
       [ 2127.,  1904.,   199.,   221.,  1201.,   250.,  1119.,   377.,
         1633.,  1801.,  2011.,  1794.,   394.,   238.,   206.,   680.],
       [  435.,  1703.,  1385.,  1461.,   213.,  1211.,   192.,  1553.,
         1580.,   197.,   571.,   195.,   326.,  1491.,   869.,  1282.],
       [  109.,   104.,  3033.,   120.,   652.,  2752.,  1822.,  2518.,
         1289.,  1053.,  1397.,   951.,  3015.,  3016.,   125.,  1782.],
       [ 2025.,  1920.,  1891.,    99.,  1057.,  1909.,  2237.,   106.,
           97.,   920.,   603.,  1841.,  2150.,  1980.,  1970.,    88.],
       [ 1870.,   170.,   167.,   176.,   306.,  1909.,  1825.,  1709.,
          168.,  1400.,   359.,   817.,  1678.,  1718.,  1

In [5]:
min = np.amin(input_array, 1)
max = np.amax(input_array, 1)

In [6]:
sum(max - min)

36174.0

In [7]:
def checks(array_i):
    min = np.amin(array_i, 1)
    max = np.amax(array_i, 1)
    return sum(max - min)

In [8]:
test = np.array([[5, 1, 9, 5], [7, 5, 3, 3], [2, 4, 6, 8]])


In [9]:
checks(input_array)

36174.0

In [72]:
def dividemin(vector):
    m = np.argmin(vector)
    modules = np.delete(vector, m) % vector[m]
    if np.any(modules == 0):
        return np.asscalar(np.delete(vector, m)[np.argwhere(modules == 0)]) // vector[m] 
    else:
        return dividemin(np.delete(vector,m))

In [73]:
vector = np.array([2, 5, 35])
m = np.argmin(vector)
print(m)
modules = np.delete(vector, m) % vector[m]
print(modules)
print(np.any(modules == 0))

0
[1 1]
False


In [74]:
dividemin(np.array([3, 8, 6, 5]))

[3 8 6 5]


2

In [77]:
sum(np.apply_along_axis(arr=input_array, axis=1, func1d=dividemin))

[ 3751.  3769.  2769.  2039.  2794.   240.  3579.  1228.  4291.   220.
   324.  3960.   211.  1346.   237.  1586.]
[ 3751.  3769.  2769.  2039.  2794.   240.  3579.  1228.  4291.   220.
   324.  3960.  1346.   237.  1586.]
[ 550.  589.  538.  110.  167.  567.   99.  203.  524.  288.  500.  111.
  118.  185.  505.   74.]
[ 550.  589.  538.  110.  167.  567.   99.  203.  524.  288.  500.  111.
  118.  185.  505.]
[ 550.  589.  538.  110.  167.  567.  203.  524.  288.  500.  111.  118.
  185.  505.]
[ 2127.  1904.   199.   221.  1201.   250.  1119.   377.  1633.  1801.
  2011.  1794.   394.   238.   206.   680.]
[ 2127.  1904.   221.  1201.   250.  1119.   377.  1633.  1801.  2011.
  1794.   394.   238.   206.   680.]
[ 2127.  1904.   221.  1201.   250.  1119.   377.  1633.  1801.  2011.
  1794.   394.   238.   680.]
[ 2127.  1904.  1201.   250.  1119.   377.  1633.  1801.  2011.  1794.
   394.   238.   680.]
[  435.  1703.  1385.  1461.   213.  1211.   192.  1553.  1580.   197.
   571.  

244.0

In [19]:
vector[np.argwhere(modules == 0)]

array([[5]])